"""Add rendered_html cache and indexes to Post model

Revision ID: 715a0231e659
Revises: 7e166c8fb8f7
Create Date: 2025-10-25 03:26:32.696718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715a0231e659'
down_revision = '7e166c8fb8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rendered_html', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_status'))
        batch_op.drop_index(batch_op.f('ix_post_date_posted'))
        batch_op.drop_column('rendered_html')

    # ### end Alembic commands ###
